security:
    providers:
        in_memory: { memory: ~ }
        user_provider: 
            entity:
                class:      App\Entity\User
                property:   username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: user_provider
            form_login:
                login_path:             login
                check_path:             login
                default_target_path:    / 
            logout:
                path:                   /logout
                target:                 /
       
            
    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 13

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used


    # access_control:
        #- { path: ^/(users|post), roles: ROLE_USER }
        #- { path: ^/admin, roles: ROLE_ADMIN }
