#index:
#    path: /
#    controller: App\Controller\DefaultController::index


admin:
    path:       /admin
    controller: App\Controller\AdminController::admin

signup:
    path:       /signup/{invitationId}
    controller: App\Controller\SignupController::signup

group_list:
    path:       /admin/groups
    controller: App\Controller\AdminController::listGroups

homepage:
    path:       /
    controller: App\Controller\DefaultController::homepage
  
login:
    path:       /login
    controller: App\Controller\DefaultController::login
    
logout:
    path:       /logout

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
    
profile:
    path:       /profile
    controller: App\Controller\ProfileController::profile

profile_edit:
    path:       /profile/edit
    controller: App\Controller\ProfileController::profileEdit

picture_edit:
    path:       /profile/picture
    controller: App\Controller\PictureController::pictureEdit

user_list:
    path:       /users
    controller: App\Controller\SearchController::listUsers

post:
    path:       /post
    controller: App\Controller\PostController::createPost

post_list:
    path:       /posts
    controller: App\Controller\PostController::listPosts


flag_post:
    path:       /post/{post}/flag
    controller: App\Controller\PostController::flagPost


